-- MySQL Script generated by MySQL Workbench
-- Wed Jun 11 14:55:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cadastro_Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadastro_Usuário` (
  `idCadastro_Usuário` INT NOT NULL AUTO_INCREMENT,
  `CPF` CHAR(11) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idCadastro_Usuário`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico_Padaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servico_Padaria` (
  `idCadastro_usuario` INT NOT NULL,
  `Salário` VARCHAR(45) NULL,
  `Horas Trabalhadas` VARCHAR(45) NULL,
  `Função` VARCHAR(45) NULL,
  `HorasExtras` VARCHAR(45) NULL,
  `Faltas_Justificadas` VARCHAR(45) NULL,
  PRIMARY KEY (`idCadastro_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cadastro_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadastro_usuario` (
  `idCadastro_usuario` INT NOT NULL,
  `nome` INT NULL,
  `gmail` INT NULL,
  `cpf` CHAR(11) NULL,
  `cep` CHAR(8) NULL,
  `telefone` CHAR(9) NULL,
  `servico_surpermercado_` INT NOT NULL,
  PRIMARY KEY (`idCadastro_usuario`),
  INDEX `fk_Cadastro_usuario_servico_surpermercado1_idx` (`servico_surpermercado_` ASC) VISIBLE,
  CONSTRAINT `fk_Cadastro_usuario_servico_surpermercado1`
    FOREIGN KEY (`servico_surpermercado_`)
    REFERENCES `mydb`.`servico_surpermercado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servico_surpermercado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servico_surpermercado` (
  `ID` INT NOT NULL,
  `salario` VARCHAR(45) NULL,
  `turno` VARCHAR(45) NULL,
  `horas trabalhadas` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `hora extra` VARCHAR(45) NULL,
  `servico_surpermercadocol` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cadastro_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadastro_usuario` (
  `idCadastro_usuario` INT NOT NULL,
  `nome` INT NULL,
  `gmail` INT NULL,
  `cpf` CHAR(11) NULL,
  `cep` CHAR(8) NULL,
  `telefone` CHAR(9) NULL,
  `servico_surpermercado_` INT NOT NULL,
  PRIMARY KEY (`idCadastro_usuario`),
  INDEX `fk_Cadastro_usuario_servico_surpermercado1_idx` (`servico_surpermercado_` ASC) VISIBLE,
  CONSTRAINT `fk_Cadastro_usuario_servico_surpermercado1`
    FOREIGN KEY (`servico_surpermercado_`)
    REFERENCES `mydb`.`servico_surpermercado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
